import type { TestDefinition } from './types';

export const TEST_REGISTRY: TestDefinition[] = [
  {
    slug: 'reaction-time',
    name: 'Reaction Time',
    description: 'Measure your visual reflex speed across 5 rounds.',
    category: 'human-benchmark',
    icon: '⚡',
    scoreUnit: 'ms',
    direction: 'lower',
    leaderboardEnabled: true,
  },
  {
    slug: 'chimp-test',
    name: 'Chimp Test',
    description: 'Memorize positions and click numbers in ascending order.',
    category: 'human-benchmark',
    icon: '🐒',
    scoreUnit: 'level',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'typing',
    name: 'Typing Test',
    description: 'Type a passage quickly with high accuracy.',
    category: 'human-benchmark',
    icon: '⌨️',
    scoreUnit: 'wpm',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'visual-memory',
    name: 'Visual Memory',
    description: 'Remember flashing tiles as grid complexity grows.',
    category: 'human-benchmark',
    icon: '🧠',
    scoreUnit: 'level',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'aim-trainer',
    name: 'Aim Trainer',
    description: 'Hit 30 targets with speed and precision.',
    category: 'human-benchmark',
    icon: '🎯',
    scoreUnit: 'ms/target',
    direction: 'lower',
    leaderboardEnabled: true,
  },
  {
    slug: 'number-memory',
    name: 'Number Memory',
    description: 'Recall ever-longer random numbers.',
    category: 'human-benchmark',
    icon: '🔢',
    scoreUnit: 'digits',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'verbal-memory',
    name: 'Verbal Memory',
    description: 'Mark words as NEW or SEEN before lives run out.',
    category: 'human-benchmark',
    icon: '📚',
    scoreUnit: 'count',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'sequence-memory',
    name: 'Sequence Memory',
    description: 'Repeat an expanding visual sequence.',
    category: 'human-benchmark',
    icon: '🟦',
    scoreUnit: 'level',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'symbol-search',
    name: 'Symbol Search',
    description: 'Find matching symbols under time pressure.',
    category: 'human-benchmark',
    icon: '🔍',
    scoreUnit: 'correct/90s',
    direction: 'higher',
    leaderboardEnabled: true,
    timeLimitSeconds: 90,
  },
  {
    slug: 'color-blindness',
    name: 'Color Blindness',
    description: 'Ishihara-style plates for color vision screening.',
    category: 'human-benchmark',
    icon: '🎨',
    scoreUnit: 'classification',
    direction: 'higher',
    leaderboardEnabled: false,
  },
  {
    slug: 'face-memory',
    name: 'Face Memory',
    description: 'Study and recognize faces across increasing levels.',
    category: 'human-benchmark',
    icon: '🙂',
    scoreUnit: 'percent',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'hue-test',
    name: 'Hue Test',
    description: 'Pick the tile with a subtle hue difference.',
    category: 'human-benchmark',
    icon: '🌈',
    scoreUnit: 'level',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'object-tracking',
    name: 'Object Tracking',
    description: 'Track highlighted circles while they move.',
    category: 'human-benchmark',
    icon: '🛰️',
    scoreUnit: 'level',
    direction: 'higher',
    leaderboardEnabled: true,
  },
  {
    slug: 'gia-reasoning',
    name: 'GIA Reasoning',
    description: 'Answer logic comparisons with sign-flipped phrasing.',
    category: 'gia',
    icon: '🧩',
    scoreUnit: 'net',
    direction: 'higher',
    leaderboardEnabled: true,
    timeLimitSeconds: 120,
  },
  {
    slug: 'gia-perceptual-speed',
    name: 'GIA Perceptual Speed',
    description: 'Count case-insensitive letter matches across columns.',
    category: 'gia',
    icon: '⚙️',
    scoreUnit: 'net',
    direction: 'higher',
    leaderboardEnabled: true,
    timeLimitSeconds: 120,
  },
  {
    slug: 'gia-number-speed',
    name: 'GIA Number Speed',
    description: 'Pick the value furthest from the middle number.',
    category: 'gia',
    icon: '➗',
    scoreUnit: 'net',
    direction: 'higher',
    leaderboardEnabled: true,
    timeLimitSeconds: 120,
  },
  {
    slug: 'gia-word-meaning',
    name: 'GIA Word Meaning',
    description: 'Choose the odd word out as fast as possible.',
    category: 'gia',
    icon: '📝',
    scoreUnit: 'net',
    direction: 'higher',
    leaderboardEnabled: true,
    timeLimitSeconds: 120,
  },
  {
    slug: 'gia-spatial',
    name: 'GIA Spatial',
    description: 'Detect same-letter pairs under rotation and mirror rules.',
    category: 'gia',
    icon: '🧭',
    scoreUnit: 'net',
    direction: 'higher',
    leaderboardEnabled: true,
    timeLimitSeconds: 120,
  },
  {
    slug: 'gia-combined',
    name: 'GIA Combined',
    description: 'Combined rank from all 5 timed GIA subtests in a single session.',
    category: 'gia',
    icon: '🏁',
    scoreUnit: 'net',
    direction: 'higher',
    leaderboardEnabled: true,
    playable: false,
  },
];

export const TEST_REGISTRY_BY_SLUG = new Map(TEST_REGISTRY.map((test) => [test.slug, test]));

export function getTestBySlug(slug: string): TestDefinition | null {
  return TEST_REGISTRY_BY_SLUG.get(slug) ?? null;
}

export function listTestsByCategory(category: TestDefinition['category']): TestDefinition[] {
  return TEST_REGISTRY.filter((test) => test.category === category);
}

export function listPlayableTestsByCategory(category: TestDefinition['category']): TestDefinition[] {
  return TEST_REGISTRY.filter((test) => test.category === category && test.playable !== false);
}
